import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={inter.className + ' ' + 'h-screen grid grid-rows-[auto_1fr_auto] text-center'}
      >
        <header className="m-10 text-2xl">My Next.js App</header>

        <main className="flex flex-col items-center">
          {/* page.tsx */}
          {children}
        </main>

        <footer className="m-4 text-sm">
          Made by <a href="https://github.com/webdev4422">webdev4422</a>
        </footer>
      </body>
    </html>
  )
}
